id: I1BD9A1E8
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:05:53.891834+00:00
last_modified: 2022-12-14 18:05:53.891840+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-091-074
  eft-text-version: 1.0.5 2021
  title: Toh_676-The_Dharani_Essence_of_Immeasurable_Longevity_and_Wisdom-v1
bases:
  '2963':
    source_metadata: null
    order: 1
    base_file: 2963.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
